"""GraphClaw domain models — public re-exports.

Import from this package rather than from individual sub-modules so that
internal organisation can evolve without breaking callers.
"""

# Enumerations
from graphclaw.models.enums import (
    AutonomyLevel,
    AvailabilityStatus,
    BreakdownStrategy,
    ChangedBy,
    CheckinState,
    CompletionSignal,
    ConfidenceLevel,
    ConstraintScope,
    ConstraintType,
    EdgeCreatedBy,
    EdgeStrength,
    EdgeType,
    GateType,
    GoalOrigin,
    GoalPriority,
    GoalState,
    MatchedBy,
    OverrideType,
    ResourceType,
    RiskLevel,
    TaskState,
    TaskType,
)

# Base / ID utilities
from graphclaw.models.base import (
    CHECKIN_NODE_ID_PATTERN,
    CONSTRAINT_ID_PATTERN,
    EDGE_ID_PATTERN,
    GOAL_ID_PATTERN,
    RESOURCE_ID_PATTERN,
    TASK_ID_PATTERN,
    USER_ID_PATTERN,
    BaseNode,
    generate_checkin_node_id,
    generate_constraint_id,
    generate_edge_id,
    generate_goal_id,
    generate_resource_id,
    generate_task_id,
    generate_user_id,
    utcnow,
    validate_constraint_id,
    validate_edge_id,
    validate_goal_id,
    validate_resource_id,
    validate_task_id,
    validate_user_id,
)

# Type-metadata models
from graphclaw.models.type_metadata import (
    ApprovalMetadata,
    AtomicMetadata,
    CheckinMetadata,
    CompositeMetadata,
    DecisionMetadata,
    DelegatedMetadata,
    FollowUpMetadata,
    MilestoneMetadata,
    RecurringMetadata,
    ResearchMetadata,
    ReviewMetadata,
    TypeMetadata,
)

# Node models
from graphclaw.models.nodes import (
    AutonomyBlock,
    AutonomyDefaults,
    BehavioralModel,
    CapacityModel,
    CheckinNode,
    CheckinResolution,
    CommunicationPreferences,
    ConstraintNode,
    ConstraintRule,
    CurrentRisk,
    EmbeddingInputs,
    GoalNode,
    GoalProgress,
    GoalTimeline,
    OverrideBlock,
    ProgressBlock,
    ReliabilityModel,
    ResourceNode,
    RiskSignal,
    ScoringBlock,
    ScoringWeights,
    StateHistoryEntry,
    TaskNode,
    Timeline,
    UpdateLogEntry,
    UserNode,
    UserPreferences,
    WorkingHours,
)

# Edge models
from graphclaw.models.edges import (
    AppliesToProps,
    AssignedToProps,
    BatchedInProps,
    BlocksProps,
    BranchedFromProps,
    DependsOnProps,
    EdgeProperties,
    FollowUpForProps,
    GraphEdge,
    InformsProps,
    OwnedByProps,
    PartOfProps,
    SpawnedFromProps,
)

# Scoring / explainability models
from graphclaw.models.scoring import (
    ActionQueueEntry,
    ScoreExplanation,
    ScoreFactor,
    ScoreModifier,
)

__all__ = [
    # Enums
    "AutonomyLevel",
    "AvailabilityStatus",
    "BreakdownStrategy",
    "ChangedBy",
    "CheckinState",
    "CompletionSignal",
    "ConfidenceLevel",
    "ConstraintScope",
    "ConstraintType",
    "EdgeCreatedBy",
    "EdgeStrength",
    "EdgeType",
    "GateType",
    "GoalOrigin",
    "GoalPriority",
    "GoalState",
    "MatchedBy",
    "OverrideType",
    "ResourceType",
    "RiskLevel",
    "TaskState",
    "TaskType",
    # ID patterns
    "TASK_ID_PATTERN",
    "USER_ID_PATTERN",
    "GOAL_ID_PATTERN",
    "CONSTRAINT_ID_PATTERN",
    "RESOURCE_ID_PATTERN",
    "EDGE_ID_PATTERN",
    "CHECKIN_NODE_ID_PATTERN",
    # ID generators
    "generate_task_id",
    "generate_user_id",
    "generate_goal_id",
    "generate_constraint_id",
    "generate_resource_id",
    "generate_edge_id",
    "generate_checkin_node_id",
    "utcnow",
    # ID validators
    "validate_task_id",
    "validate_user_id",
    "validate_goal_id",
    "validate_constraint_id",
    "validate_resource_id",
    "validate_edge_id",
    # Base
    "BaseNode",
    # Type metadata
    "AtomicMetadata",
    "DelegatedMetadata",
    "FollowUpMetadata",
    "ApprovalMetadata",
    "CompositeMetadata",
    "MilestoneMetadata",
    "ReviewMetadata",
    "RecurringMetadata",
    "DecisionMetadata",
    "CheckinMetadata",
    "ResearchMetadata",
    "TypeMetadata",
    # Node sub-models
    "Timeline",
    "ScoringBlock",
    "StateHistoryEntry",
    "ProgressBlock",
    "OverrideBlock",
    "AutonomyBlock",
    "UpdateLogEntry",
    "EmbeddingInputs",
    "ScoringWeights",
    "AutonomyDefaults",
    "UserPreferences",
    "BehavioralModel",
    "WorkingHours",
    "GoalTimeline",
    "GoalProgress",
    "ConstraintRule",
    "CapacityModel",
    "ReliabilityModel",
    "RiskSignal",
    "CurrentRisk",
    "CommunicationPreferences",
    "CheckinResolution",
    # Node types
    "TaskNode",
    "UserNode",
    "GoalNode",
    "ConstraintNode",
    "ResourceNode",
    "CheckinNode",
    # Edge property sub-models
    "DependsOnProps",
    "PartOfProps",
    "BlocksProps",
    "FollowUpForProps",
    "SpawnedFromProps",
    "AssignedToProps",
    "OwnedByProps",
    "AppliesToProps",
    "InformsProps",
    "BranchedFromProps",
    "BatchedInProps",
    "EdgeProperties",
    # Edge
    "GraphEdge",
    # Scoring
    "ScoreFactor",
    "ScoreModifier",
    "ScoreExplanation",
    "ActionQueueEntry",
]
